%macro  set_symbol  1

  %ifdef Linux
    %define %1 %1
  %elifdef Darwin
    %define %1 _%1
  %else
    %error "environment not supported"
  %endif

%endmacro

%macro  global_   1

  set_symbol  %1
  global  %1

%endmacro

%macro  extern_   1

  set_symbol  %1
  extern  %1

%endmacro

%macro  call_extern_   1

  %ifidn __OUTPUT_FORMAT__,elf64
    call  %1 WRT ..plt
  %else
    call  %1
  %endif

%endmacro
